spring:
  application:
    name: vault
  cloud:
    vault:
      kv:
        enabled: true
        backend: secret
        application-name: test
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:root}
      scheme: http
      host: ${SPRING_CLOUD_VAULT_HOST:localhost}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      enabled: true
      connection-timeout: 5000
      read-timeout: 15000

  config:
    import: vault://secret/application
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: dev01
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8888






