spring:
  application:
    name: vault
  cloud:
    vault:
      kv:
        enabled: true
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:root}
      scheme: http
      host: ${SPRING_CLOUD_VAULT_HOST:localhost}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      enabled: true
      connection-timeout: 50000
      read-timeout: 30000
  config:
    import: vault://secret/application
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 7777777
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8888






