spring:
  application:
    name: vault
  cloud:
    vault:
      kv:
        enabled: true
      authentication: TOKEN
      token: ${SPRING_CLOUD_VAULT_TOKEN:root}
      scheme: http
      host: ${SPRING_CLOUD_VAULT_HOST:localhost}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      enabled: true
      connection-timeout: 50000
      read-timeout: 30000
  config:
    import: vault://secret/application
server:
  port: 8870






